{% set name = "rustpython" %}
{% set version = "0.4.0" %}
{% set build = 0 %}
{% set sha256 = "17aae8666e09bd8489fa3c0df300bb96922b4f2e11d78bcbd63cbf606a95d5d8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/RustPython/RustPython/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - rust

test:
  commands:
    - rustpython -c "print('hello')"

about:
  home: https://github.com/RustPython/RustPython
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python-3 (CPython >= 3.5.0) Interpreter written in Rust
  dev_url: https://github.com/RustPython/RustPython

extra:
  recipe-maintainers:
    - davidbrochart
